/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nzetmyuxjfhlmvwoqkrv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZXRteXV4amZobG12d29xa3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTMzMzQsImV4cCI6MjA3MTk2OTMzNH0.S__7w37Hny-O-kqfyz7U5MVZ7SZlsoIsQY8PurhVkQM"